Enrollment System Beta/ctu/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('enrollment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Enrollment System Beta/enrollment/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # User URL...
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    # New Student URL...
    path('new-student/dashboard/', views.newStudentPage, name="newStudentPage"),
    path('new-student/update-information/<str:pk>/',
         views.newStudentUpdateInfo, name='newStudentUpdateInfo'),
    path('new-student/display-information/', views.displayNewStudentInfo,
         name="displayNewStudentInfo"),
    path('new-student/profile/', views.newStudentProfile, name="newStudentProfile"),

    # BSIT Student URL...
    path('bsit-student/dashboard/', views.bsitStudentPage, name="bsitStudentPage"),
    path('bsit-student/update-information/<str:pk>/',
         views.bsitStudentUpdateInfo, name='bsitStudentUpdateInfo'),
    path('bsit-student/display-information/', views.displayBsitStudentInfo,
         name="displayBsitStudentInfo"),
    path('bsit-student/profile/', views.bsitStudentProfile,
         name="bsitStudentProfile"),

    # BIT Student URL...
    path('bit-student/dashboard/', views.bitStudentPage, name="bitStudentPage"),
    path('bit-student/update-information/<str:pk>/',
         views.bitStudentUpdateInfo, name='bitStudentUpdateInfo'),
    path('bit-student/display-information/', views.displayBitStudentInfo,
         name="displayBitStudentInfo"),
    path('bit-student/profile/', views.bitStudentProfile, name="bitStudentProfile"),

    # Faculty URL...
    path('faculty/', views.facultyPage, name="faculty"),

    # Student Subject Form
    path('subject-form-1/', views.studentSubjectForm1,
         name="studentSubjectForm1"),
    path('subject-form-2/',
         views.studentSubjectForm2, name="studentSubjectForm2"),
    path('ajax/load-year_levels/', views.load_year_levels,
         name='ajax_load_year_levels'),
    path('ajax/load-semesters/', views.load_semesters, name='ajax_load_semesters'),
    path('ajax/load-enrollment_statuses/', views.load_enrollment_statuses,
         name='ajax_load_enrollment_statuses'),

    # User Password Reset
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="enrollment/user/password/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="enrollment/user/password/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="enrollment/user/password/password_reset_form.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="enrollment/user/password/password_reset_done.html"),
         name="password_reset_complete"),

]

Enrollment System Beta/enrollment/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

from django.utils import timezone


class UserManager(BaseUserManager):

    def create_user(self, email,
                    full_name=None,
                    first_name=None,
                    middle_name=None,
                    last_name=None,
                    address=None,
                    mobile_num=None,
                    congressional_district=None,
                    gender=None,
                    birth_place=None,
                    birth_date=None,
                    age=None,
                    citizenship=None,
                    religion=None,
                    civil_status=None,
                    father_name=None,
                    father_occupation=None,
                    mother_name=None,
                    mother_occupation=None,
                    guardian_name=None,
                    guardian_phone_number=None,
                    elementary=None,
                    elementary_academic_year=None,
                    elementary_honors_received=None,
                    high_school=None,
                    high_school_academic_year=None,
                    high_school_honors_received=None,
                    college=None,
                    college_academic_year=None,
                    college_honors_received=None, password=None,
                    is_new_student=True,
                    is_bsit_student=False,
                    is_bit_student=False,
                    is_active=True,  is_staff=False, is_admin=False):
        """
        Creates and saves a User with the given email and password.
        """

        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError("Users must have a password")

        # def phone_number_isValid(phone1, phone2):
        #     Pattern = re.compile("(0)?[11][0-9]{9}")
        #     return Pattern.match(phone1, phone2)

        # if (phone_number_isValid(mobile_num, guardian_phone_number)):
        user_obj = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            middle_name=middle_name,
            last_name=last_name,
            address=address,
            mobile_num=mobile_num,
            congressional_district=congressional_district,
            gender=gender,
            birth_place=birth_place,
            birth_date=birth_date,
            age=age,
            citizenship=citizenship,
            religion=religion,
            civil_status=civil_status,
            father_name=father_name,
            father_occupation=father_occupation,
            mother_name=mother_name,
            mother_occupation=mother_occupation,
            guardian_name=guardian_name,
            guardian_phone_number=guardian_phone_number,
            elementary=elementary,
            elementary_academic_year=elementary_academic_year,
            elementary_honors_received=elementary_honors_received,
            high_school=high_school,
            high_school_academic_year=high_school_academic_year,
            high_school_honors_received=high_school_honors_received,
            college=college,
            college_academic_year=college_academic_year,
            college_honors_received=college_honors_received
        )
        # else:
        #     raise ValueError("Invalid Phone Number")

        user_obj.set_password(password)  # change user password
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.new_student = is_new_student
        user_obj.bsit_student = is_bsit_student
        user_obj.bit_student = is_bit_student
        user_obj.is_active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, full_name=None, password=None):
        user = self.create_user(
            email,
            full_name=full_name,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, email, full_name=None, password=None):
        user = self.create_user(
            email,
            full_name=full_name,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)

    # persnol information
    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    CIVIL_STATUS = (
        ('Single', 'Single'),
        ('Married', 'Married'),
        ('Divorced', 'Divorced'),
        ('Widow', 'Widow'),
    )

    full_name = models.CharField(max_length=255, blank=True, null=True)

    profile_pic = models.ImageField(
        default="defaultprofile.png", null=True, blank=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    mobile_num = models.CharField(max_length=11, blank=True, null=True)
    congressional_district = models.CharField(
        max_length=50, blank=True, null=True)
    gender = models.CharField(
        max_length=50, blank=True, choices=GENDER, null=True)
    birth_place = models.CharField(max_length=50, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    citizenship = models.CharField(max_length=50, blank=True, null=True)
    religion = models.CharField(max_length=50, blank=True, null=True)
    civil_status = models.CharField(
        max_length=50, blank=True, choices=CIVIL_STATUS, null=True)
    father_name = models.CharField(max_length=50, blank=True, null=True)
    father_occupation = models.CharField(max_length=50, blank=True, null=True)
    mother_name = models.CharField(max_length=50, blank=True, null=True)
    mother_occupation = models.CharField(max_length=50, blank=True, null=True)
    guardian_name = models.CharField(max_length=50, blank=True, null=True)
    guardian_phone_number = models.CharField(
        max_length=11, blank=True, null=True)
    elementary = models.CharField(max_length=50, blank=True, null=True)
    elementary_academic_year = models.CharField(
        max_length=50, blank=True, null=True)
    elementary_honors_received = models.CharField(
        max_length=50, blank=True, null=True)
    high_school = models.CharField(max_length=50, blank=True, null=True)
    high_school_academic_year = models.CharField(
        max_length=50, blank=True, null=True)
    high_school_honors_received = models.CharField(
        max_length=50, blank=True, null=True)
    college = models.CharField(max_length=50, blank=True, null=True)
    college_academic_year = models.CharField(
        max_length=50, blank=True, null=True)
    college_honors_received = models.CharField(
        max_length=50, blank=True, null=True)

    new_student = models.BooleanField(default=True)
    bsit_student = models.BooleanField(default=False)
    bit_student = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)  # staff user non superuser
    admin = models.BooleanField(default=False)  # superuser
    timestamp = models.DateTimeField(auto_now_add=True)

    # notice the absence of a "Password field", that is built in.

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []  # Email & Password are required by default.

    objects = UserManager()

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_new_student(self):
        return self.new_student

    @property
    def is_bsit_student(self):
        return self.bsit_student

    @property
    def is_bit_student(self):
        return self.bit_student

    @property
    def is_staff(self):
        "Is the user a member of staff?"

        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

# Subject Form


class Course(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class YearLevel(models.Model):
    Year_Level = (
        ('1st', '1st'),
        ('2nd', '2nd'),
        ('3rd', '3rd'),
        ('4th', '4th'),
    )
    name = models.CharField(max_length=30, blank=True,
                            null=True, choices=Year_Level)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Semester(models.Model):
    Semesters = (
        ('1st', '1st'),
        ('2nd', '2nd'),
    )
    name = models.CharField(max_length=30, blank=True,
                            null=True, choices=Semesters)
    year_level = models.ForeignKey(YearLevel, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Subject(models.Model):

Enrollment System Beta/enrollment/templates/enrollment/student/new/dashboard.html
{%  extends 'enrollment/student/new/template.html' %}
<h1>New Student - Dashboard</h1>

Enrollment System Beta/enrollment/templates/enrollment/student/new/profile.html
{%  extends 'enrollment/user/template.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static '/css/student/profile.css' %}">
<div class="card">
    <a href="{% url 'newStudentPage' %}" onclick="history.go(-1)"><i class="fa fa-arrow-circle-left" style="font-size: 36px;"></i></a>
    <div class="row">
        <div class="col">
            <div class="profile-pic-div">
                <img src="{{request.user.profile_pic.url}}" id="photo">
                <input type="file" id="file">
                <label for="file" id="uploadBtn">Choose Profile</label>
            </div>
        </div>
        <div class="col">
            <form class="user">
                <div class="form-group">
                    <label class="left" for="fn">Full Name: {{user.first_name}} {{user.middle_name}} {{user.last_name}}</label>
                    
                </div>
                <div class="form-group">
                    <label class="left" for="usr">Username: {{user.email}}</label>
                    
                </div>
                <div class="form-group">
                    <a href="#" class="btn">
                        Change Password
                    </a>
                </div>
            </form>

        </div>
    </div>

    <hr>
    <div class="text-center">
        <a href="{% url 'newStudentPage' %}" class="btn btn-sucess">
            Save Changes
        </a>
    </div>
</div>
<script src="{% static '/js/student/profile.js' %}"></script>
{% endblock content %}

Enrollment System Beta/enrollment/templates/enrollment/student/new/prospectus.html
upcoming

Enrollment System Beta/enrollment/templates/enrollment/student/new/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'newStudentPage' %}">
        <div class="sidebar-brand-text mx-1">Enrollment System - New Student</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'newStudentPage' %}">
            <img class="img-profile rounded-circle profile-pic img-fluid" src="{{request.user.profile_pic.url}}" >
            <span>My Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <li class="nav-item">
      <a class="nav-link" href="{% url 'displayNewStudentInfo' %}">
          <i class="fa fa-edit"></i>
          <span>View Personal Information</span></a>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'newStudentUpdateInfo' user.id%}">
            <i class="fa fa-edit"></i>
            <span>Update Personal Information</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-file-alt"></i>
          <span>Prospectos ( Subject Guide Only )</span>
      </a>
      <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
              <h4 class="collapse-header">BSIT Prospectus:</h4>
              <a class="collapse-item" href="bs1.html">1st year</a>
              <a class="collapse-item" href="bs2.html">2nd year</a>
              <a class="collapse-item" href="bs3.html">3rd year</a>
              <a class="collapse-item" href="bs4.html">4th year</a>
              <h4 class="collapse-header">BIT-CT Prospectus:</h4>
              <a class="collapse-item" href="bt1.html">1st year</a>
              <a class="collapse-item" href="bt2.html">2nd year</a>
              <a class="collapse-item" href="bt3.html">3rd year</a>
              <a class="collapse-item" href="bt4.html">4th year</a>
          </div>
      </div>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'studentSubjectForm1' %}">
            <i class="far fa-file-alt"></i>
            <span>Subject Form</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="#">
            <i class="fas fa-layer-group"></i>
            <span>Requirements</span></a>
    </li>


    <!-- Nav Item - Track -->
    <li class="nav-item">
        <a class="nav-link" href="#">
            <i class="fa fa-spinner"></i>
            <span>Track Enrollment Progress</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

Enrollment System Beta/enrollment/templates/enrollment/student/new/subject_form1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="container">
      <form method="post" id="personForm" data-year_levels-url="{% url 'ajax_load_year_levels' %}" novalidate>
        {% csrf_token %}
            <div class="row">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td colspan="2">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroup-sizing-sm">ID Number: {{form.id_number}}</span>
                                        </div>
                                    </div>
                                </td>
                                <td colspan="2">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="inputGroupSelect01">Course</label>
                                        </div>
                                        {{form.course}}
                                    </div>
                                </td>
                                <td colspan="2">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroup-sizing-sm">Major: {{form.major}}</span>
                                        </div>
                                    </div>
                                </td>
                                <td colspan="2">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="inputGroupSelect01">Year Level</label>
                                        </div>
                                        {{form.year_level}}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroup-sizing-sm">School Year: {{form.school_year}}</span>
                                        </div>
                                    </div>
                                </td>
                                <td colspan="2">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="inputGroupSelect01">Semester</label>
                                        </div>
                                        {{form.semester}}
                                    </div>
                                </td>
                                <td colspan="4">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="inputGroupSelect01">Enrolment Status</label>
                                        </div>
                                        {{form.enrollment_status}}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="inputGroupSelect01">Enrolment Status</label>
                                        </div>
                                        {{form.student_status}}
                                    </div>
                                </td>
                                <td colspan="4">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroup-sizing-sm">Block Section: {{form.block_section}}</span>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
            </div>
        <button type="submit">Save</button>
      </form>
    </div>
    
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_course").change(function () {
      var url = $("#personForm").attr("data-year_levels-url");  // get the url of the `load_year_levels` view
      var courseId = $(this).val();  // get the selected course ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: "{% url 'ajax_load_year_levels' %}",                    // set the url of the request (= localhost:8000/hr/ajax/load-year_levels/)
        data: {
          'course': courseId       // add the course id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_year_levels` view function
          $("#id_year_level").html(data);  // replace the contents of the year_level input with the data that came from the server
        }
      });

    });
    // this one is for fetching semester data
    $("#id_year_level").change(function () { //django-model-form created this id
      var url = $("#personForm").attr("data-year_levels-url");  // get the url of the `load_year_levels` view
      var year_levelId = $(this).val();  // get the selected course ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: "{% url 'ajax_load_semesters' %}",                    // set the url of the request (= localhost:8000/hr/ajax/load-year_levels/) person_form.html template has this url var
        data: {
          'year_level': year_levelId       // add the course id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_year_levels` view function
          $("#id_semester").html(data);  // replace the contents of the year_level input with the data that came from the server
        }
      });

    });

    $("#id_semester").change(function () { //django-model-form created this id
      var url = $("#personForm").attr("data-semesters-url");  // get the url of the `load_year_levels` view
      var semesterId = $(this).val();  // get the selected course ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: "{% url 'ajax_load_enrollment_statuses' %}",                    // set the url of the request (= localhost:8000/hr/ajax/load-year_levels/) person_form.html template has this url var
        data: {
          'semester': semesterId       // add the course id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_year_levels` view function
          $("#id_enrollment_status").html(data);  // replace the contents of the year_level input with the data that came from the server
        }
      });

    });
  </script>

</body>
</html>

Enrollment System Beta/enrollment/templates/enrollment/student/new/template.html
{%load static%}
<!DOCTYPE html>
<html>
	<head>
		<title>CTU-Ginatilan</title>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
        {% include 'enrollment/base/student/css.html' %}
	</head>
	<body >
		<!-- Page Wrapper -->
		<div id="wrapper">
			<!-- Sidebar -->
			{% include 'enrollment/student/new/sidebar.html' %}
			<!-- End of Sidebar -->
				<!-- Content Wrapper -->
				<div id="content-wrapper" class="d-flex flex-column">
					<!-- Main Content -->
					<div id="content">
						<!-- Topbar -->
						{% include 'enrollment/student/new/topbar.html' %}
						<!-- End of Topbar -->
							{% block content %}
							
							{% endblock %}
					</div>
					<!-- End of Main Content -->
				</div>
				<!-- End of Content Wrapper -->
		</div>
		<!-- End of Page Wrapper -->
	</body>

	{% include 'enrollment/base/student/js.html' %}
	<!-- <script src="{% static '/base/vendor/jquery/jquery.min.js' %}"></script> -->
	<!-- <script src="{% static '/base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> -->
	
	<!-- Core plugin JavaScript-->
	<!-- <script src="{% static '/base/vendor/jquery-easing/jquery.easing.min.js' %}"></script> -->
	
	<!-- Custom scripts for all pages-->
	<script src="{% static 'js/student/main.js' %}"></script>  
    
</html>

Enrollment System Beta/enrollment/templates/enrollment/student/new/topbar.html
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <div class="topleftbar-divider d-none d-sm-block"></div>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Hello, {{request.user}}</span>
                        <img class="img-profile rounded-circle profile-pic" src="{{request.user.profile_pic.url}}">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{% url 'newStudentProfile' %}">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout
                        </a>
                    </div>
                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->